version: 1.0.{build}.{branch}
image: Visual Studio 2017
configuration: Release
platform: x64

environment:
  matrix:
    - nodejs_version: '10'

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install yarn -g
  - yarn install

before_build:
  - set PATH=%QTDIR%\bin;%PATH%

build_script:
  - yarn run build

artifacts:
  - path: build
    name: build

matrix:
  fast_finish: false

on_failure:
  - echo Failed

test_script:
  - yarn test -- --no-watchman
